spring.application.name=streamvault
spring.datasource.url=jdbc:mysql://localhost:3306/streamvault
spring.datasource.username=root
spring.datasource.password=Beijing@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true